version: "3"

services:
  docker_registry:
    restart: always
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - docker_registry_data:/var/lib/registry

  cdn:
    image: gsmlg/npm-cdn:latest
    volumes:
      - npm_cdn_mirrors:/mirrors
    ports:
      - 127.0.0.1:10002:80
    restart: unless-stopped

  stunnel:
    image: gsmlg/proxy:stunnel
    restart: unless-stopped
    environment:
      - PROXY_MODE
      - PROXY_SERVER
    volumes:
      - certs:/etc/certs:ro
    ports:
      - 13128:443
      - 3128:80

  npm_registry:
    image: sisk/npm-registry-couchapp:2.6.10
    restart: unless-stopped
    volumes:
      - couch_logs:/usr/local/var/log/couchdb
      - couch_data:/usr/local/var/lib/couchdb

  kappa:
    image: sisk/kappa:1.0.0-rc.14
    depends_on:
      - npm_registry
    ports:
      - 127.0.0.1:10001:8000
    restart: unless-stopped
    volumes:
      - ./config.tmpl:/opt/kappa/config.json


volumes:
  couch_logs: {}
  couch_data: {}
  npm_cdn_mirrors: {}
  docker_registry_data: {}
  certs: {}


