version: "3"

services:
  docker_registry:
    restart: always
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - docker_registry_data:/var/lib/registry

  cdn:
    image: gsmlg/npm-cdn:latest
    volumes:
      - npm_cdn_mirrors:/mirrors
    ports:
      - 127.0.0.1:10002:80
    restart: unless-stopped

  npm_registry:
    image: sisk/npm-registry-couchapp:2.6.10
    restart: unless-stopped
    volumes:
      - couch_logs:/usr/local/var/log/couchdb
      - couch_data:/usr/local/var/lib/couchdb

  kappa:
    image: sisk/kappa:1.0.0-rc.14
    depends_on:
      - npm_registry
    ports:
      - 127.0.0.1:10001:8000
    restart: unless-stopped
    volumes:
      - ./config.tmpl:/opt/kappa/config.json

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=beforeCloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    image: nextcloud
    ports:
      - 10800:80
    links:
      - db
    volumes:
      - /nextcloud/data:/var/www/html
    restart: always

  rancher:
    image: rancher/rancher
    restart: unless-stopped
    ports:
      - 10080:80
      - 10443:443

  singlecloud:
    image: zdnscloud/singlecloud:latest
    restart: unless-stopped
    ports:
      - 10880:80
    
  stunnel:
    image: gsmlg/proxy:stunnel
    restart: unless-stopped
    environment:
      - PROXY_MODE=slave
      - PROXY_SERVER=sg.gsmlg.org
    volumes:
      - certs:/etc/certs:ro
    ports:
      - 3128:80


volumes:
  couch_logs: {}
  couch_data: {}
  npm_cdn_mirrors: {}
  docker_registry_data: {}
  certs: {}
  nextcloud:
  db:


